env:
  global:
    - CC_TEST_REPORTER_ID=141be9862dc0f3388f8d4e3c9de84ad880bdceb42cab4e0ab46373750638e00c
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: php

php:
  - 7.0
  - 7.1

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPSTAN=1 DEFAULT=1
    - php: 7.1
      env: PHPSTAN=1 DEFAULT=1

install:
  - composer self-update
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.9; fi

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.0 ]]; then vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 4 src; fi

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
email: false