language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 7.0
      env: PHPSTAN=1 DEFAULT=0
    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

install:
  - if [ $TRAVIS_PHP_VERSION != 7.2 ]; then phpenv config-rm xdebug.ini; fi
  - composer install

before_script:
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.9; fi

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.0 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 4 src; fi

notifications:
email: false